#docker run -it --rm \
#    -v synapse_data,dst=/data \
#    -e SYNAPSE_SERVER_NAME=matrix.example.com \
#    -e SYNAPSE_REPORT_STATS=no \
#    matrixdotorg/synapse:latest generate

#edit homeserver.yaml, include workers
#create worker.yaml

#set custom locations in npm for workers

services:
  mjolnir:
    image: ${MJOLNIR_IMAGE}
    restart: unless-stopped
    volumes:
      - mjolnir_data:/data
    networks:
      - matrix-network-v6
    depends_on:
      synapse-app:
        condition: service_healthy
        restart: true
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - matrix-network-v6
    volumes:
      - redis_data:/data
  synapse-app:
    image: ${SYNAPSE_IMAGE}
    restart: unless-stopped
    ports:
      - '8008:8008'
      #- '8448:8448'
    volumes:
      - synapse_data:/data
      - synapse_sockets:/sockets
    networks:
      matrix-network-v6:
      ingress-network-v6:
      monitoring-network-v6:
    depends_on:
      - redis
    environment:
      - SYNAPSE_SERVER_NAME=matrix.techlife.home64.de
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - SYNAPSE_WORKER=synapse.app.homeserver
    healthcheck:
      test: ["CMD", "curl", "-fSs", "http://localhost:8008/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
  worker-federation-sender:
    image: ${SYNAPSE_IMAGE}
    restart: unless-stopped
    volumes:
      - synapse_data:/data
      - synapse_sockets:/sockets
    networks:
      - matrix-network-v6
      - monitoring-network-v6
    environment:
      - SYNAPSE_SERVER_NAME=matrix.techlife.home64.de
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - SYNAPSE_WORKER=synapse.app.generic_worker
    depends_on:
      - synapse-app
      - redis
    command:
      - "run"
      - "-m"
      - "synapse.app.generic_worker" # Startet den generischen Worker-Prozess...
      - "--config-path"
      - "/data/homeserver.yaml"      # ...lädt zuerst die Hauptkonfiguration...
      - "--config-path"
      - "/data/federation_sender.yaml" # ...und dann die Worker-spezifische Konfiguration.
    healthcheck:
      test: ["CMD", "curl", "-fSs", "http://localhost:9096/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
  worker-federation-sender-2:
    image: ${SYNAPSE_IMAGE}
    restart: unless-stopped
    volumes:
      - synapse_data:/data
      - synapse_sockets:/sockets
    networks:
      - matrix-network-v6
      - monitoring-network-v6
    environment:
      - SYNAPSE_SERVER_NAME=matrix.techlife.home64.de
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - SYNAPSE_WORKER=synapse.app.generic_worker
    depends_on:
      - synapse-app
      - redis
    command:
      - "run"
      - "-m"
      - "synapse.app.generic_worker" # Startet den generischen Worker-Prozess...
      - "--config-path"
      - "/data/homeserver.yaml"      # ...lädt zuerst die Hauptkonfiguration...
      - "--config-path"
      - "/data/federation_sender_2.yaml" # ...und dann die Worker-spezifische Konfiguration.
    healthcheck:
      test: ["CMD", "curl", "-fSs", "http://localhost:9096/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
  worker-federation-sender-3:
    image: ${SYNAPSE_IMAGE}
    restart: unless-stopped
    volumes:
      - synapse_data:/data
      - synapse_sockets:/sockets
    networks:
      - matrix-network-v6
      - monitoring-network-v6
    environment:
      - SYNAPSE_SERVER_NAME=matrix.techlife.home64.de
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - SYNAPSE_WORKER=synapse.app.generic_worker
    depends_on:
      - synapse-app
      - redis
    command:
      - "run"
      - "-m"
      - "synapse.app.generic_worker" # Startet den generischen Worker-Prozess...
      - "--config-path"
      - "/data/homeserver.yaml"      # ...lädt zuerst die Hauptkonfiguration...
      - "--config-path"
      - "/data/federation_sender_3.yaml" # ...und dann die Worker-spezifische Konfiguration.
    healthcheck:
      test: ["CMD", "curl", "-fSs", "http://localhost:9096/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
  worker-federation-sender-4:
    image: ${SYNAPSE_IMAGE}
    restart: unless-stopped
    volumes:
      - synapse_data:/data
      - synapse_sockets:/sockets
    networks:
      - matrix-network-v6
      - monitoring-network-v6
    environment:
      - SYNAPSE_SERVER_NAME=matrix.techlife.home64.de
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - SYNAPSE_WORKER=synapse.app.generic_worker
    depends_on:
      - synapse-app
      - redis
    command:
      - "run"
      - "-m"
      - "synapse.app.generic_worker" # Startet den generischen Worker-Prozess...
      - "--config-path"
      - "/data/homeserver.yaml"      # ...lädt zuerst die Hauptkonfiguration...
      - "--config-path"
      - "/data/federation_sender_4.yaml" # ...und dann die Worker-spezifische Konfiguration.
    healthcheck:
      test: ["CMD", "curl", "-fSs", "http://localhost:9096/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
  worker-stream-writer:
    image: ${SYNAPSE_IMAGE}
    restart: unless-stopped
    volumes:
      - synapse_data:/data
      - synapse_sockets:/sockets
    networks:
      matrix-network-v6:
      ingress-network-v6:
        ipv4_address: 172.18.0.4
        ipv6_address: fd42:dead:beef:c0de:1::4
      monitoring-network-v6:
    environment:
      - SYNAPSE_SERVER_NAME=matrix.techlife.home64.de
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - SYNAPSE_WORKER=synapse.app.generic_worker
    depends_on:
      - synapse-app
      - redis
    command:
      - "run"
      - "-m"
      - "synapse.app.generic_worker" # Startet den generischen Worker-Prozess...
      - "--config-path"
      - "/data/homeserver.yaml"      # ...lädt zuerst die Hauptkonfiguration...
      - "--config-path"
      - "/data/stream_writer.yaml" # ...und dann die Worker-spezifische Konfiguration.
    healthcheck:
      test: ["CMD", "curl", "-fSs", "http://localhost:9095/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
  worker-stream-writer-2:
    image: ${SYNAPSE_IMAGE}
    restart: unless-stopped
    volumes:
      - synapse_data:/data
      - synapse_sockets:/sockets
    networks:
      matrix-network-v6:
      ingress-network-v6:
        ipv4_address: 172.18.0.5
        ipv6_address: fd42:dead:beef:c0de:1::5
      monitoring-network-v6:
    environment:
      - SYNAPSE_SERVER_NAME=matrix.techlife.home64.de
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - SYNAPSE_WORKER=synapse.app.generic_worker
    depends_on:
      - synapse-app
      - redis
    command:
      - "run"
      - "-m"
      - "synapse.app.generic_worker" # Startet den generischen Worker-Prozess...
      - "--config-path"
      - "/data/homeserver.yaml"      # ...lädt zuerst die Hauptkonfiguration...
      - "--config-path"
      - "/data/stream_writer_2.yaml" # ...und dann die Worker-spezifische Konfiguration.
    healthcheck:
      test: ["CMD", "curl", "-fSs", "http://localhost:9096/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
  worker-federation-reader:
    image: ${SYNAPSE_IMAGE}
    restart: unless-stopped
    volumes:
      - synapse_data:/data
      - synapse_sockets:/sockets
    networks:
      matrix-network-v6:
      ingress-network-v6:
        ipv4_address: 172.18.0.6
        ipv6_address: fd42:dead:beef:c0de:1::6
      monitoring-network-v6:
    environment:
      - SYNAPSE_SERVER_NAME=matrix.techlife.home64.de
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - SYNAPSE_WORKER=synapse.app.generic_worker
    depends_on:
      - synapse-app
      - redis
    command:
      - "run"
      - "-m"
      - "synapse.app.generic_worker" # Startet den generischen Worker-Prozess...
      - "--config-path"
      - "/data/homeserver.yaml"      # ...lädt zuerst die Hauptkonfiguration...
      - "--config-path"
      - "/data/federation_reader.yaml" # ...und dann die Worker-spezifische Konfiguration.
    healthcheck:
      test: ["CMD", "curl", "-fSs", "http://localhost:9094/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
  worker-background-worker:
    image: ${SYNAPSE_IMAGE}
    restart: unless-stopped
    volumes:
      - synapse_data:/data
      - synapse_sockets:/sockets
    networks:
      matrix-network-v6:
      ingress-network-v6:
        ipv4_address: 172.18.0.11
        ipv6_address: fd42:dead:beef:c0de:1::11
      monitoring-network-v6:
    environment:
      - SYNAPSE_SERVER_NAME=matrix.techlife.home64.de
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - SYNAPSE_WORKER=synapse.app.generic_worker
    depends_on:
      - synapse-app
      - redis
    command:
      - "run"
      - "-m"
      - "synapse.app.generic_worker" # Startet den generischen Worker-Prozess...
      - "--config-path"
      - "/data/homeserver.yaml"      # ...lädt zuerst die Hauptkonfiguration...
      - "--config-path"
      - "/data/background_worker.yaml" # ...und dann die Worker-spezifische Konfiguration.
    healthcheck:
      test: ["CMD", "curl", "-fSs", "http://localhost:9097/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
  synapse-admin:
    image: ${SYNAPSE_ADMIN_IMAGE}
    restart: unless-stopped
    ports:
      - '8085:80'
    volumes:
      - synapse_data:/data
    networks:
      - matrix-network-v6
    depends_on:
      - synapse-app
volumes:
  synapse_data:
    external: true
  redis_data:
    name: redis_data
    external: true
  synapse_sockets:
    name: synapse_sockets
    driver_opts:
      type: tmpfs
      device: tmpfs
  mjolnir_data:
    name: mjolnir_data
    external: true
networks:
  matrix-network-v6:
    name: matrix-network-v6
    external: true
  ingress-network-v6:
    name: ingress-network-v6
    external: true
  monitoring-network-v6:
    name: monitoring-network-v6
    external: true

#docker exec -it synapse-container-name register_new_matrix_user http://localhost:8008 -c /data/homeserver.yaml