#docker run -it --rm \
#    -v synapse_data,dst=/data \
#    -e SYNAPSE_SERVER_NAME=matrix.example.com \
#    -e SYNAPSE_REPORT_STATS=no \
#    matrixdotorg/synapse:latest generate

#edit homeserver.yaml, include workers
#create worker.yaml

#set custom locations in npm for workers

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - matrix-network-v6
    volumes:
      - redis_data:/data
  synapse-app:
    image: matrixdotorg/synapse:latest
    restart: unless-stopped
    ports:
      - '8008:8008'
      #- '8448:8448'
    volumes:
      - synapse_data:/data
      - postgres_sockets:/var/run/postgresql
      - synapse_sockets:/sockets
    networks:
      - matrix-network-v6
      - ingress-network-v6
    depends_on:
      - redis
    environment:
      - SYNAPSE_SERVER_NAME=matrix.techlife.home64.de
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - SYNAPSE_WORKER=synapse.app.homeserver
  worker-federation-sender:
    image: matrixdotorg/synapse:latest
    restart: unless-stopped
    volumes:
      - synapse_data:/data
      - postgres_sockets:/var/run/postgresql
      - synapse_sockets:/sockets
    networks:
      - matrix-network-v6
    environment:
      - SYNAPSE_SERVER_NAME=matrix.techlife.home64.de
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - SYNAPSE_WORKER=synapse.app.generic_worker
    depends_on:
      - synapse-app
      - redis
    command:
      - "run"
      - "-m"
      - "synapse.app.generic_worker"
      - "--config-path"
      - "/data/homeserver.yaml"
      - "--config-path"
      - "/data/federation_sender.yaml"
    healthcheck:
      test: ["CMD", "curl", "-fSs", "http://localhost:9096/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 60s
  worker-federation-sender-2:
    image: matrixdotorg/synapse:latest
    restart: unless-stopped
    volumes:
      - synapse_data:/data
      - postgres_sockets:/var/run/postgresql
      - synapse_sockets:/sockets
    networks:
      - matrix-network-v6
    environment:
      - SYNAPSE_SERVER_NAME=matrix.techlife.home64.de
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - SYNAPSE_WORKER=synapse.app.generic_worker
    depends_on:
      - synapse-app
      - redis
    command:
      - "run"
      - "-m"
      - "synapse.app.generic_worker"
      - "--config-path"
      - "/data/homeserver.yaml"
      - "--config-path"
      - "/data/federation_sender_2.yaml"
    healthcheck:
      test: ["CMD", "curl", "-fSs", "http://localhost:9096/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 60s
  worker-stream-writer:
    image: matrixdotorg/synapse:latest
    restart: unless-stopped
    volumes:
      - synapse_data:/data
      - postgres_sockets:/var/run/postgresql
      - synapse_sockets:/sockets
    networks:
      - matrix-network-v6
      - ingress-network-v6
    environment:
      - SYNAPSE_SERVER_NAME=matrix.techlife.home64.de
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - SYNAPSE_WORKER=synapse.app.generic_worker
    depends_on:
      - synapse-app
      - redis
    command:
      - "run"
      - "-m"
      - "synapse.app.generic_worker"
      - "--config-path"
      - "/data/homeserver.yaml"
      - "--config-path"
      - "/data/stream_writer.yaml"
    healthcheck:
      test: ["CMD", "curl", "-fSs", "http://localhost:9095/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 60s
  worker-stream-writer-2:
    image: matrixdotorg/synapse:latest
    restart: unless-stopped
    volumes:
      - synapse_data:/data
      - postgres_sockets:/var/run/postgresql
      - synapse_sockets:/sockets
    networks:
      - matrix-network-v6
      - ingress-network-v6
    environment:
      - SYNAPSE_SERVER_NAME=matrix.techlife.home64.de
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - SYNAPSE_WORKER=synapse.app.generic_worker
    depends_on:
      - synapse-app
      - redis
    command:
      - "run"
      - "-m"
      - "synapse.app.generic_worker"
      - "--config-path"
      - "/data/homeserver.yaml"
      - "--config-path"
      - "/data/stream_writer_2.yaml"
    healthcheck:
      test: ["CMD", "curl", "-fSs", "http://localhost:9096/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 60s
  worker-federation-reader:
    image: matrixdotorg/synapse:latest
    restart: unless-stopped
    volumes:
      - synapse_data:/data
      - postgres_sockets:/var/run/postgresql
      - synapse_sockets:/sockets
    networks:
      - matrix-network-v6
      - ingress-network-v6
    environment:
      - SYNAPSE_SERVER_NAME=matrix.techlife.home64.de
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - SYNAPSE_WORKER=synapse.app.generic_worker
    depends_on:
      - synapse-app
      - redis
    command:
      - "run"
      - "-m"
      - "synapse.app.generic_worker" # Startet den generischen Worker-Prozess...
      - "--config-path"
      - "/data/homeserver.yaml"      # ...lädt zuerst die Hauptkonfiguration...
      - "--config-path"
      - "/data/federation_reader.yaml" # ...und dann die Worker-spezifische Konfiguration.
    healthcheck:
      test: ["CMD", "curl", "-fSs", "http://localhost:9094/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 60s
  synapse-admin:
    image: awesometechnologies/synapse-admin:latest
    restart: unless-stopped
    ports:
      - '8085:80'
    volumes:
      - synapse_data:/data
    networks:
      - matrix-network-v6
    depends_on:
      - synapse-app
volumes:
  synapse_data:
    external: true
  postgres_sockets:
    external: true
  redis_data:
    name: redis_data
    external: true
  synapse_sockets:
    name: synapse_sockets
    driver_opts:
      type: tmpfs
      device: tmpfs
networks:
  matrix-network-v6:
    name: matrix-network-v6
    external: true
  ingress-network-v6:
    name: ingress-network-v6
    external: true

#docker exec -it synapse-container-name register_new_matrix_user http://localhost:8008 -c /data/homeserver.yaml