services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=Europe/Berlin
    #user: 1000:1000
    volumes:
      - ntfy_cache:/var/cache/ntfy
      - ntfy_data:/etc/ntfy
    networks:
      - ingress-network-v6
    healthcheck:
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 60s
    restart: unless-stopped
volumes:
  ntfy_cache:
    external: true
  ntfy_data:
    external: true
networks:
  ingress-network-v6:
    name: ingress-network-v6
    external: true
