services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pW
      POSTGRES_USER: uSer
      POSTGRES_DB: dB
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --locale=C'
      PGDATA: /var/lib/postgresql/data/17/docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - matrix-network
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - matrix-network
volumes:
  postgres_data:
    external: true
networks:
  matrix-network:
    name: matrix-network
    external: true
