services:
  db:
    image: postgres:17
    restart: unless-stopped

    environment:
      POSTGRES_PASSWORD: pW
      POSTGRES_USER: uSer
      POSTGRES_DB: synapse
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --locale=C'
      PGDATA: /var/lib/postgresql/data/17/docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_sockets:/var/run/postgresql
    networks:
      - matrix-network-v6
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8082:8080
    networks:
      - matrix-network-v6
volumes:
  postgres_data:
    external: true
  postgres_sockets:
    name: postgres_sockets
    driver_opts:
      type: tmpfs
      device: tmpfs
networks:
  matrix-network-v6:
    name: matrix-network-v6
    external: true