global:
  scrape_interval: 15s # Metriken alle 15 Sekunden abrufen

rule_files:
  - "/etc/prometheus/synapse-v2.rules"


scrape_configs:
  #- job_name: 'prometheus'
  #  static_configs:
  #    - targets: ['localhost:9090']

  #- job_name: 'node-exporter'
  #  static_configs:
  #    - targets: ['node-exporter:9100']

  #- job_name: 'cadvisor'
  #  static_configs:
  #    - targets: ['cadvisor:8080']

  - job_name: "synapse"
    scrape_interval: 15s
    metrics_path: "/_synapse/metrics"
    static_configs:
      - targets: ["synapse-app:9000"]
        labels:
          instance: "matrix.techlife.home64.de"
          job: "master"
          index: 1
      - targets: ["worker-federation-sender:9101"]
        labels:
          instance: "matrix.techlife.home64.de"
          job: "worker-federation-sender"
          index: 1
      - targets: ["worker-federation-sender-2:9101"]
        labels:
          instance: "matrix.techlife.home64.de"
          job: "worker-federation-sender-2"
          index: 1
      - targets: ["worker-federation-sender-3:9101"]
        labels:
          instance: "matrix.techlife.home64.de"
          job: "worker-federation-sender-3"
          index: 1
      - targets: ["worker-federation-sender-4:9101"]
        labels:
          instance: "matrix.techlife.home64.de"
          job: "worker-federation-sender-4"
          index: 1
      - targets: ["worker-stream-writer:9102"]
        labels:
          instance: "matrix.techlife.home64.de"
          job: "worker-stream-writer"
          index: 1
      - targets: ["worker-stream-writer-2:9102"]
        labels:
          instance: "matrix.techlife.home64.de"
          job: "worker-stream-writer-2"
          index: 1
      - targets: ["worker-federation-reader:9103"]
        labels:
          instance: "matrix.techlife.home64.de"
          job: "worker-federation-reader"
          index: 1
      - targets: ["worker-background-worker:9104"]
        labels:
          instance: "matrix.techlife.home64.de"
          job: "worker-background-worker"
          index: 1

  - job_name: "ntfy"
    scrape_interval: 15s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["ntfy:9090"]
        labels:
          instance: "ntfy.techlife.home64.de"
          job: "ntfy-metrics"
          index: 1

  - job_name: "crowdsec"
    scrape_interval: 15s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["crowdsec:6060"]
        labels:
          instance: "srv-01"
          job: "crowdsec-metrics"
          index: 1